name: agri_disease_app
description: A new Flutter project for plant disease detection and remedies.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  go_router: ^14.2.0
  equatable: ^2.0.5
  cached_network_image: ^3.3.1
  fpdart: ^1.1.0
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  path_provider: ^2.1.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
